config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',     to: 'static_pages#about'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, 	  only: [:new, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> &copy; 2020 Yuya Kage All Rights Reserved.</small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "キャンパスナビ", root_path, id: "logo" %>
    </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
       <ul class="nav navbar-nav navbar-right">
         <% if logged_in? %>
           <li><%= link_to "授業アドバイスを書く", new_micropost_path  %></li>
           <li><%= link_to "授業一覧", root_path %></li>
           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント情報 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー一覧", users_path  %></li>
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
           </li>
         <% else %>
           <li><%= link_to "キャンパスナビとは", about_path %></li>
           <li><%= link_to "ユーザー登録(無料)",  signup_path %></li>
           <li><%= link_to "ログイン", login_path %></li>
         <% end %>
       </ul>
     </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>